version: 2
jobs:
  unit:
    docker:
      - image: circleci/node:8.12.0

    working_directory: ~/unit

    steps:
      - checkout

      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      - run:
          name: Installing dependencies
          command: yarn install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      - run:
          name: Running tests
          command: yarn test

  deploy:
    docker:
      - image: circleci/node:8.12.0

    working_directory: ~/deploy
    steps:
      - checkout

      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      - run:
          name: Installing dependencies
          command: yarn install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      - run:
          name: Creating package
          command: yarn pack

workflows:
  version: 2
  test_and_deploy:
    jobs:
      - unit
      - deploy:
          requires:
            - unit
          filters:
            branches:
              only: /release-.*/
