version: 2
jobs:
  unit:
    docker:
      - image: circleci/node:12.13.0

    working_directory: ~/unit

    steps:
      - checkout

      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      - run:
          name: Installing dependencies
          command: yarn install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      - run:
          name: Setting up Code Climate test reporter
          command: |
            curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
            chmod +x ./cc-test-reporter

      - run:
          name: Running tests
          command: |
            ./cc-test-reporter before-build
            yarn test --coverage
      
      - run:
          name: Reporting test coverage to Code Climate
          command: |
            ./cc-test-reporter after-build -t lcov --exit-code $? coverage/

  deploy:
    docker:
      - image: circleci/node:12.13.0

    working_directory: ~/deploy
    steps:
      - checkout

      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      - run:
          name: Installing dependencies
          command: yarn install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      - run:
          name: Publishing new release
          command: yarn ci-publish

workflows:
  version: 2
  test_and_deploy:
    jobs:
      - unit
      - deploy:
          requires:
            - unit
          filters:
            branches:
              only:
                - /release-.*/
                - master
